config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :admins
  devise_for :users
  scope "(:locale)", locale: /ja|en/ do
    get "tasks/index" => "tasks#index"
    resources :tasks#, format: false

    resources :users, :only => [:index, :edit, :update], format: false
  end

  namespace :api do
    resources :tasks#, only: [:index, :show, :create]
  end

  root to: "tasks#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: {in: 5..100, allow_blank: true}, uniqueness: { scope: :user_id }

  belongs_to :user

  after_create :send_contact_email

  def late?
    due_on.in_time_zone < Date.current.in_time_zone
  end

  def user_name
    user.name
  end

  def send_contact_email
    Admin.all.each do |admin|
      ContactToCreateTaskMailer.contact_email(self, admin).deliver_later
      # ContactToCreateTaskMailer.contact_email(self, admin).deliver_now
    end
    ContactToCreateTaskMailer.confirmation_email(self).deliver_later
  end
end

app/controllers/api/tasks_controller.rb
module Api
  class TasksController < ApplicationController

    prepend_before_action :authenticate_user_from_token!

    def index
      @tasks = current_user.tasks
      render json: @tasks
    end

    def show
      @task = Task.find(params[:id])
      render json: @task
    end

    def create
      @task = current_user.tasks.new(task_params)

      if @task.save
        render json: { status: :created }
      else
        render json: @task.errors, status: :unprocessable_entity
      end
    end

    private

    def authenticate_user_from_token!
      user_email = params[:user_email].presence
      user = user_email && User.find_by(email: user_email)
      if user && Devise.secure_compare(user.authentication_token, params[:user_token])
        sign_in user, store: true
      else
        render json: { status: "auth failed" }
        false
      end
    end

    def task_params
      params.require(:task).permit(:content, :finished, :due_on)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :task_owner?, only: [:show, :edit, :update, :destroy]
  
  
  # GET /tasks
  def index
    @tasks = current_user.tasks
    # json_hash =
    #   GetWebAPI.new(
    #     "http://api.atnd.org/events/",
    #     {
    #       keyword_or: "ruby",
    #       format: "json"
    #     },
    #     logger).response
    # json_hash["events"] && json_hash["events"].each do |event|
    #   if event["event"] && event["event"]["address"] =~ /東京/
    #     event =
    #       Event.find_or_initialize_by(
    #         url: event["event"]["event_url"]
    #       )
    #     if event.new_record?
    #       event.title = event["event"]["title"],
    #       event.address = event["event"]["address"],
    #       event.started_at = event["event"]["started_at"]
    #       event.save
    #     end
    #   end
    # end
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)
    @task.user = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: t(".notice", model: Task.model_name.human) }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: t(".notice", model: Task.model_name.human) }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: t(".notice", model: Task.model_name.human) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content, :finished)
    end

    def task_owner?
      if @task && (@task.user == current_user)
        #logger.debug "task_owner"
      else
        redirect_to root_path, alert: "自身以外のタスクにアクセスできません。"
      end
    end
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= t(:problem) %></h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :finished %>
    <%= form.check_box :finished %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn-square" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= Task.model_name.human %> <%=t :edit%></h1>

<%= render 'form', task: @task %>

<%= link_to t(:list), tasks_path %>

app/views/tasks/index.html.erb
<h1><%= Task.model_name.human %> <%= t :list %></h1>

<% if @tasks.count > 0 %>
<table>
  <thead>
    <tr>
      <th><%=Task.human_attribute_name :content %></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <% if task.finished %>
          <td>
            <strike><%= link_to task.content, task %></strike>
            <%=link_to "[x]", task_url(task), { method: :delete, class: :cmd, data: { confirm: "本当に削除しますか？" }} %>
          </td>
        <% else %>
          <td><%= link_to task.content, task %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p><%= t(".register_task") %></p>
<% end %>
<br>

<%= link_to t(:create), new_task_path, class: "btn-square" %>

app/views/tasks/new.html.erb
<h1><%= Task.model_name.human %> <%=t(:create)%></h1>

<%= render 'form', task: @task %>

<%= link_to t(:back), tasks_path, class: "btn-square" %>

app/views/tasks/show.html.erb
<p>
  <strong><%= Task.human_attribute_name :finished %>:</strong>
  <%= @task.finished %>
</p>
<p>
  <strong><%= Task.human_attribute_name :content %></strong>
  <%= @task.content %>
</p>

<%= link_to t(:edit), edit_task_path(@task), class: "btn-square" %>
<%= link_to t(:back), tasks_path, class: "btn-square" %>